artifactory:
  masterKeySecretName: artifactory-master-key
  joinKeySecretName: artifactory-join-key
  image:
    tag: "7.77.3"  # Replace with the desired Artifactory version

# databaseUpgradeReady: true

# postgresql:
#   image:
#     tag: 16.6.0-debian-12-r2
